### ISSUE TITLE
Error running dev prereq install and install

### ISSUE THREAD

**Issue by dinger1986** [ninjamonkey198206/tacticalrmm#3]
Downloaded and ran wget https://raw.githubusercontent.com/ninjamonkey198206/tacticalrmm/develop-installer-update-ws/installer-util.sh (chmod etc first)

So ran install for prereqs, errored out, I did put in the settings wrong the first time as in put in the complete domain not just the subdomain. 

I used rmm.flonix.co.uk and m. a. r. as the subdomains.

/home/tactical/script-cfg/NetworkFunctions.cfg: line 48: [: too many arguments
/home/tactical/script-cfg/NetworkFunctions.cfg: line 26: 1
10+1: syntax error in expression (error token is "10+1")

**Comment by ninjamonkey198206** [comment]
That has to do with checking for and adding localhost if it's not there. Do you have multiple entries that use 127.0.0.1, vs 127.0.1.1?

**Comment by dinger1986** [comment]
It's a new build Ubuntu 20.04 install on hetzner

**Comment by ninjamonkey198206** [comment]
Can you send me the /etc/hosts file? just need to see the 127.x.x.x IPs and how many entries/order they're in.
Just tested on my clean ubuntu 20.04 vm and couldn't replicate the issue, so there must be a difference that I'll have to rewrite the function to account for.

**Comment by dinger1986** [comment]
```
127.0.0.1       localhost
# Your system has configured 'manage_etc_hosts' as True.
# As a result, if you wish for changes to this file to persist
# then you will need to either
# a.) make changes to the master file in /etc/cloud/templates/hosts.debian.tmpl
# b.) change or remove the value of 'manage_etc_hosts' in
#     /etc/cloud/cloud.cfg or cloud-config from user-data
#
127.0.1.1 ubuntu-4gb-fsn1-1 ubuntu-4gb-fsn1-1
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by ninjamonkey198206** [comment]
The fuck? Yeah, All the garbage they threw in is likely causing the issue. Used to seeing a clean file with 127.0.0.1 localhost as the first entry. Pretty sure the method I use can't account for all that garbage.

**Comment by ninjamonkey198206** [comment]
I'll have to figure out a new way of doing it that takes stuff like that into account

**Comment by ninjamonkey198206** [comment]
```bash
sed -n "/127.0.0.1/=" /etc/hosts
```
try running that and see what you get

**Comment by dinger1986** [comment]
lol yeah not fun, hosts files are similar on other cloud hosts. Could clear the file?

**Comment by ninjamonkey198206** [comment]
I may have to, but I'd need to pull all pertinent info first and replace it after clearing it

**Comment by dinger1986** [comment]
tactical@ubuntu-4gb-fsn1-1:~$ sed -n "/127.0.0.1/=" /etc/hosts
1
10

**Comment by ninjamonkey198206** [comment]
Wait... Did you run it again on the same vhd after you input the wrong domain info, and I assume killed it mid run?

**Comment by ninjamonkey198206** [comment]
I'm gonna have to build in the same file reversion method I used in my server script or something.

**Comment by ninjamonkey198206** [comment]
'Cause localhost should only be in the file once, not twice.

**Comment by ninjamonkey198206** [comment]
That's why it's throwing the error

**Comment by dinger1986** [comment]
> Wait... Did you run it again on the same vhd after you input the wrong domain info, and I assume killed it mid run?

well the script gave me the option to put the info back in again, I didnt run it again

**Comment by dinger1986** [comment]
this is another hosts file on hetzner

```
# Your system has configured 'manage_etc_hosts' as True.
# As a result, if you wish for changes to this file to persist
# then you will need to either
# a.) make changes to the master file in /etc/cloud/templates/hosts.debian.tmpl
# b.) change or remove the value of 'manage_etc_hosts' in
#     /etc/cloud/cloud.cfg or cloud-config from user-data
#
127.0.1.1 ubuntu-2gb-nbg1-1 ubuntu-2gb-nbg1-1
127.0.0.1 localhost

# The following lines are desirable for IPv6 capable hosts
::1 localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

```

**Comment by ninjamonkey198206** [comment]
So that worked correctly, now to figure out why localhost ipv4 is in there twice.

**Comment by ninjamonkey198206** [comment]
I'll check the order of that and make sure the localhost check can't run until after the URLs have been verified.

**Comment by dinger1986** [comment]
could that file be cleared?

**Comment by ninjamonkey198206** [comment]
Probably. Would just need to grab the first 127.0.1.1 entries, truncate it, then spit localhost, the 127.0.1.1 entries out, then the IPv6 entries

**Comment by dinger1986** [comment]
yeah would think so

**Comment by ninjamonkey198206** [comment]
I think I fixed this and a few other quirks, most notably an issue with the cfg file version check for updating them individually.

Ran devprep on a VM and it worked, so we'll see how it goes on yours.

Hopefully that's the last issue, but I doubt I'm that lucky considering how major a rewrite/overhaul this was.

**Comment by ninjamonkey198206** [comment]
This particular issue was resolved.
